name: covid19cuba
description: Mobile application of Covid19 Cuba Efforts project implemented with Flutter.

version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_bloc: ^3.1.0
  equatable: ^1.0.0
  shared_preferences: ^0.5.6
  preferences: ^5.1.0
  charts_flutter: ^0.9.0
  http: ^0.12.0
  getflutter: ^1.0.0-dev.1
  flutter_launcher_icons: ^0.7.4
  url_launcher: ^5.4.1
  background_fetch: '^0.5.1'

flutter:
  uses-material-design: true

  assets:
    - assets/images/
